---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
# Add user and Group Github - Marcos Cianci
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: mcianci2024
  profile:
    email: mlopesci@nttdata.com
spec:
  memberOf: [platform]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform
spec:
  type: team
  children: []